env:
    url: http://ezqueue-dev.ap-northeast-1.elasticbeanstalk.com/ezqueue/home
spring:
    view:
        prefix: /jsp/
        suffix: .jsp
    datasource:
        url: jdbc:log4jdbc:mysql://jj.cuo6cy8ytavy.ap-northeast-1.rds.amazonaws.com:3306/ezqueue?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        username: root
        password: root0324
        driver-class-name: net.sf.log4jdbc.DriverSpy
        initial-size: 1
        max-active: 10
        min-idle: 1
        max-idle: 1
        validation-query: select 1
        test-on-borrow: true
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect